server:
  port: 8086
  servlet:
    context-path: /xiaolvxingqiu

spring:
  application:
    name: xiaolvxingqiu-boot
  datasource:
    url: jdbc:mysql://localhost:3306/skylark_xiaolvxingqiu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  auth:
    use-mock-user: true
    mock-user-id: 10001
  wechat:
    app-id: "wx2cb9ad28ce687200"
    app-secret: "2951d2edfab1a4875397798da58b6f65"
  care:
    generate-cron: "0 10 0 * * ?"
